plugin:mightymodels:
  - changed-files:
      - any-glob-to-any-file: plugins/mightymodels/**

plugin:ai-engineer:
  - changed-files:
      - any-glob-to-any-file: plugins/ai-engineer/**

ci:
  - changed-files:
      - any-glob-to-any-file: .github/**

tooling:
  - changed-files:
      - any-glob-to-any-file:
          - scripts/**
          - Makefile
          - pyproject.toml
          - uv.lock
          - .*.toml
          - .coveragerc.ini
          - .pre-commit-config.yaml

docs:
  - changed-files:
      - any-glob-to-any-file:
          - docs/**
          - "*.md"
