[pytest]
strict = true
testpaths = ["tests", "plugins"]
pythonpath = ["plugins/ai-engineer/bin"]
collect_imported_tests = false
empty_parameter_set_mark = "fail_at_collect"

faulthandler_timeout = "60"
faulthandler_exit_on_timeout = true
tmp_path_retention_policy = "failed"
tmp_path_retention_count = "3"
addopts = [
    "-ra",
    "--import-mode=importlib",
    "--tb=short",
    "--showlocals",
    "--cov",
    "--cov-config=.coveragerc.ini",
    "--cov-report=term-missing",
]

required_plugins = [
    "pytest-cov",
    "pytest-mock",
    "pytest-randomly",
    "pytest-xdist",
]
filterwarnings = ["error"]
